package org.motechproject.nms.kilkariobd.domain;

public enum CallFlowStatus {
    OUTBOUND_CALL_REQUEST_FILE_CREATED,
    OUTBOUND_CALL_REQUEST_FILE_COPIED,
    CDR_FILE_NOTIFICATION_RECEIVED,
    OUTBOUND_CALL_REQUEST_FILE_PROCESSED_AT_IVR,
    OUTBOUND_CALL_REQUEST_FILE_PROCESSING_FAILED_AT_IVR,
    CDR_FILES_PROCESSED,
    OUTBOUND_CALL_NOTIFICATION_EVENT_RECEIVED,
    OBD_FILE_NOTIFICATION_SENT_TO_IVR;
}
